apiVersion: v1
data:
  APP_SECRET_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
  USER_SECRET_KEY: xxxxxxxxxxxxxxxxx
kind: ConfigMap
metadata:
  labels:
    app: sunrise
    tier: api
  name: sunrise-config
  namespace: default
